# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Schimanski Cookbook

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
footer_links:
  - title: GitHub
    url: https://github.com/jarrodschimanski
    icon: fab fa-github-square
  - title: Twitter
    url: https://twitter.com/Jarrod_Ski
    icon: fab fa-twitter-square
  - title: 
    url: https://www.youtube.com/channel/UCRJJJmYxl4xWbRxJts8HheA
    icon: fab fa-youtube-square
  - title: 
    url: https://www.linkedin.com/in/jarrodschimanski/
    icon: fab fa-linkedin
  - title: 
    url: mailto:jarrod@schimanski.nz
    icon: fas fa-envelope-square
date_format: "%Y-%m-%d"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
skin: "/assets/css/skins/dark.css"

google_fonts:
  - name: "Roboto"
    weights: "400,400i,700,700i"


# Build settings
remote_theme: "mmistakes/so-simple-theme@3.2.0"
plugins:
  - jekyll-feed
